### ISSUE TITLE
"Made for Kids" toggle just broke

### ISSUE THREAD

**Issue by nitinthewiz** [ContentAutomation/YouTubeUploader#12]
Yesterday I noticed that YouTube moved Made For Kids to outside the "Show More" section and changed the names of the radio buttons from MADE_FOR_KIDS to VIDEO_MADE_FOR_KIDS_MFK and from NOT_MADE_FOR_KIDS to VIDEO_MADE_FOR_KIDS_NOT_MFK.

I don't know if this is true for everybody or just me, so didn't send a PR. Please check at your end and if it's true, I can send a PR or you can make the change yourself. 

I don't think the logic of the code needs to change for now, just the names of the radio buttons.

The relevant line - 
https://github.com/ContentAutomation/YouTubeUploader/blob/main/src/upload.py#L119

**Comment by ChristianCoenen** [comment]
Thanks for reporting this. I just checked on my end and can confirm that it changed. Feel free to open a PR, I'll merge it later :-)
