### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by susantha1995** [ContentAutomation/YouTubeUploader#15]
hi, please can make a short how-to video or screenshots to install and use this script correctly? this is hard to understand beginners.

**Comment by mrawesomey** [comment]
Pls help I also need

**Comment by nicenice134** [comment]
same, its impossible!

**Comment by ChristianCoenen** [comment]
Unfortunately, this YouTube uploader is not working anymore due to server-side changes from google (see https://github.com/ContentAutomation/YouTubeUploader/issues/8)
