### ISSUE TITLE
Selenium Error

### ISSUE THREAD

**Issue by NecroBoy** [ContentAutomation/YouTubeUploader#3]
When trying upload by Docker:

python3.8 main.py -B docker -l test.json -t testik -d test /uploads/videoname.mp4
INFO:root:Current progress: Upload complete ... Processing will begin shortly
INFO:root:Current progress: Processing 95% ...
INFO:root:Current progress: Processing 100% ...
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    main()
  File "main.py", line 47, in main
    upload_file(
  File "/root/YouTubeUploader/src/upload.py", line 41, in upload_file
    _set_endcard(driver)
  File "/root/YouTubeUploader/src/upload.py", line 128, in _set_endcard
    driver.find_element_by_css_selector("div.card:nth-child(1)").click()
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: div.card:nth-child(1)

Video uploaded, but Visibility is draft

**Comment by NecroBoy** [comment]
And can I disable description argument and use YouTube default description?

main.py: error: the following arguments are required: -d/--description

**Comment by lucaSchilling** [comment]
This problem is probably because YouTube regularly changes their id and classnames when they release new stuff on the youtube uploader. If you are a bit into WebDev you can try to debug it by using chromedriver/geckodriver and your local chrome/firefox browser to run our tool  with chrome/firefox you can just add the -B 'docker' or -B 'chrome' argument. 
Then you can just debug the code as usual.

If you can not resolve it @ChristianCoenen  will look into this during the next week and we will maybe provide a more detailed guide on how to debug those kind of issues.

**Comment by NecroBoy** [comment]
I fixed it, program crashes because it tries to add a cardboard at the end of video.

**Comment by nitinthewiz** [comment]
@NecroBoy  what's the resolution to the cardboard at the end? Would love to see a code patch or just your comment here? I'm also running into it regularly! It craps out and leaves the upload at the draft stage.

**Comment by NecroBoy** [comment]
> @NecroBoy what's the resolution to the cardboard at the end? Would love to see a code patch or just your comment here? I'm also running into it regularly! It craps out and leaves the upload at the draft stage.

Hello sir! You need just comment section when program tries to add cardboards.
Have a nice day!

**Comment by NecroBoy** [comment]
I can’t send fixed code because my server died (SSD died). If you can’t fix this cardboard issue just write me. I’ll help you.

**Comment by nitinthewiz** [comment]
@NecroBoy OMG that would be very helpful! Yes, the cardboard issue keeps happening every few runs. How did you debug it?? I am not even sure how to get chromedriver to stop the run!

**Comment by MorMundHS-MA** [comment]
@nitinthewiz  As far as I remember the endcard setup is optional. Can you try commenting out the `_set_endcard` call [here](https://github.com/ContentAutomation/YouTubeUploader/blob/2d69a2569006a843944af1f2e4803fb4f0942a24/src/upload.py#L41)?

If you need the endcard settings and want to fix it you can check the `_set_endcard` method, specifically [this line](https://github.com/ContentAutomation/YouTubeUploader/blob/2d69a2569006a843944af1f2e4803fb4f0942a24/src/upload.py#L128):  
``` python
driver.find_element_by_css_selector("div.card:nth-child(1)").click()
```
Likely the CSS just changed on the endcard page.
